#!/usr/bin/python
import sys,os, subprocess
import matplotlib.pyplot as plt
from influxdb import InfluxDBClient
import numpy as np
from gi.overrides.keysyms import upleftcorner
import matplotlib.mlab as mlab

def get_config(path):
    import io    
    path = os.path.abspath(path)    
    if (os.path.exists(path)):
        with io.open(path,'r') as file:
            data = eval(file.read())
        return data 
    else:
        print "path does not exists %s"%path
        sys.exit()
        

def get_low_high(avg,values):
    standard = True
    if standard==False:        
        low, high = [], []
        for value in values:
            if value>avg:
                high.append(value)
            else:
                low.append(value) 
        return np.std(low),np.std(high)  
    else:
        return np.std(values),np.std(values) 
             
def get_hour_from_timestamp(time):
    start = time.find('T') + 1
    end = time.find(':', start)
    return int(time[start:end])

def compare_monit_histsync_graph(results,server):
    fig = plt.figure() 
    fig.suptitle('Monitoring - Histogram - Different Machines\nServer: %s'%(server))
    ax = fig.add_subplot(121)
    bx = fig.add_subplot(122)
    avg_total = []
    values_upl = []
    values_dwl = []
    xTickMarks = []
    xTickGraph_a = []
    xTickGraph_b = []
    global_max = []
    for key, objs in results.items() :
        upl_values = []
        dwl_values = []
        for obj in objs[0]:
            upl_values.append(obj["value"])
        for obj in objs[1]:
            dwl_values.append(obj["value"])
        upl_values = np.array(upl_values) 
        dwl_values = np.array(dwl_values) 
        global_max.append(np.max(upl_values))
        global_max.append(np.max(dwl_values))
        values_upl.append(upl_values)
        values_dwl.append(dwl_values)
        
        xTickMarks.append(key)
    
    global_max= (np.max(global_max))   
    ax.set_xlim(left=0)
    bx.set_xlim(left=0)
    ax.set_xlim(right=global_max)
    bx.set_xlim(right=global_max)
    ax.set_ylim(top=1)
    bx.set_ylim(top=1)
    
    # the histogram of the data
    for value in values_upl:
        n, bins, patches = ax.hist(value, bins=100, cumulative=True, normed=True, histtype='step', range=(0,global_max))
        xTickGraph_a.append(patches[0])
    
    # the histogram of the data
    for value in values_dwl:
        n, bins, patches = bx.hist(value, bins=100, cumulative=True, normed=True, histtype='step', range=(0,global_max))
        xTickGraph_b.append(patches[0])
    ax.set_title('Upload Stage')
    bx.set_title('Download Stage')
    ax.set_xlabel('Synchronisation time [s]')
    ax.set_ylabel('Probability')
    bx.set_xlabel('Synchronisation time [s]')
    ax.legend(xTickGraph_a,xTickMarks)
    bx.legend(xTickGraph_b,xTickMarks)
    plt.grid(True)
    plt.tight_layout(rect=[0, 0.03, 1, 0.90])
    plt.draw()
    
def compare_monit_cm_histsync_graph(results,runid):
    fig = plt.figure() 
    ax = fig.add_subplot(111)
    avg_total = []
    values = []
    xTickMarks = []
    xTickGraph = []
    global_max = []
    for key, objs in results.items() :
        tmp_values = []
        for obj in objs:
            tmp_values.append(obj["value"])
        size = len(tmp_values)  
        tmp_values = np.array(tmp_values) 
        global_max.append(np.max(tmp_values))
        values.append(tmp_values)
        
        xTickMarks.append(key)
    
    global_max= (np.max(global_max))   
    ax.set_xlim(left=0)
    ax.set_xlim(right=global_max)
    ax.set_ylim(top=1.2)
    ind = np.arange(len(xTickMarks))                # the x locations for the groups
    width = 1                      # the width of the bars
    
    # the histogram of the data
    for value in values:
        n, bins, patches = ax.hist(value, bins=100, normed=True, cumulative=True, histtype='step', range=(0,global_max))
        xTickGraph.append(patches[0])
    
    ax.set_xlabel('Synchronisation time [s]')
    ax.set_ylabel('Probability')
    ax.legend(xTickGraph,xTickMarks)
    plt.title('Monitoring - Histogram - Different Servers\nMachine: %s'%(runid))
    plt.grid(True)
    plt.tight_layout()
    plt.draw()  
      
def compare_monit_time_graph(results,runid):
    fig = plt.figure() 
    ax = fig.add_subplot(111)
    xTickMarks = range(0,24)
    avg_total = []
    error_total_low = []
    error_total_high = []
    values = []
    for i in range(0,24):
        avg_total.append([]) 
        error_total_low.append([]) 
        error_total_high.append([]) 
        values.append([])
        
    for key, objs in results.items() :
        for obj in objs:
            hour = get_hour_from_timestamp(obj["time"])
            values[hour].append(obj["value"])
    
    for i in range(0,24): 
        avg = np.mean(np.array(values[i])) 
        low, high = get_low_high(avg,values[i])   
        avg_total[i].append(avg)   
        error_total_low[i].append(low)
        error_total_high[i].append(high)
    ## necessary variables
    ind = np.arange(len(xTickMarks))                # the x locations for the groups
    width = 1                      # the width of the bars
    # axes and labels
    for i in range(0,24):
        ax.bar(ind[i], avg_total[i], width, color='b',
                yerr=[error_total_low[i],error_total_high[i]],
                error_kw=dict(capsize=5, elinewidth=2,ecolor='black'))
    ax.set_xlim(0,len(ind))
    ax.set_ylim(bottom=0)
    ax.set_ylabel('Synchronisation Time (s)')     
    ax.set_xticks(ind)
    xtickNames = ax.set_xticklabels(xTickMarks)
    plt.setp(xtickNames, rotation=45, fontsize=10)
    plt.title('Monitoring - %s\nDistributions of synchronisation times during the day\nMachine: %s'%(key,runid))
    plt.tight_layout()
    plt.draw()
    
def compare_monit_sync_graph(results,runid):
    fig = plt.figure() 
    ax = fig.add_subplot(111)
    xTickMarks = []
    avg_total = []
    error_total_low = []
    error_total_high = []
    avg_upl = []
    error_upl_low = []
    error_upl_high = []
    avg_dwl = []
    error_dwl_low = []
    error_dwl_high = []
    for key, objs in results.items() :
        values = []
        for obj in objs[0]:
            values.append(obj["value"])
        values = np.array(values)
        avg = np.mean(values)
        low, high = get_low_high(avg,values)     
        avg_total.append(avg)   
        error_total_low.append(low)  
        error_total_high.append(high) 
        
        values = []
        for obj in objs[1]:
            values.append(obj["value"])
        values = np.array(values)
        avg = np.mean(values)
        low, high = get_low_high(avg,values)     
        avg_upl.append(avg)   
        error_upl_low.append(low)
        error_upl_high.append(high) 
        
        values = []
        for obj in objs[2]:
            values.append(obj["value"])
        values = np.array(values)
        avg = np.mean(values)
        get_low_high(avg,values)
        low, high = get_low_high(avg,values)      
        avg_dwl.append(avg)   
        error_dwl_low.append(low)
        error_dwl_high.append(high) 
        
        xTickMarks.append(key)
    ## necessary variables
    ind = np.arange(len(xTickMarks))                # the x locations for the groups
    width = 0.3                      # the width of the bars
    # axes and labels
    total = ax.bar(ind, avg_total, width, color='b',
                yerr=[error_total_low,error_total_high],
                error_kw=dict(capsize=5, elinewidth=2,ecolor='black'))
    upload = ax.bar(ind+width, avg_upl, width, color='g',
                yerr=[error_upl_low,error_upl_high],
                error_kw=dict(capsize=5, elinewidth=2,ecolor='black'))
    download = ax.bar(ind+2*width, avg_dwl, width, color='y',
                yerr=[error_dwl_low,error_dwl_high],
                error_kw=dict(capsize=5, elinewidth=2,ecolor='black'))
    ax.set_xlim(-0.1,len(ind))
    ax.set_ylim(bottom=0)
    ax.set_ylabel('Synchronisation Time (s)')     
    ax.set_xticks(ind+0.45)
    xtickNames = ax.set_xticklabels(xTickMarks)
    plt.setp(xtickNames, rotation=45, fontsize=10)
    plt.title('Monitoring - distributions of synchronisation times\nMachine: %s'%(runid))
    ## add a legend
    ax.legend((total[0], upload[0], download[0]), ('Total', 'Upload', 'Download'))
    plt.tight_layout()
    plt.draw()

def compare_files_runid(results,tot_err,server):
    fig = plt.figure() 
    fig.suptitle('Monitoring - Histogram - Different Machines\nServer: %s'%(server))
    ax = fig.add_subplot(121)
    bx = fig.add_subplot(122)
    values = []
    passed = []
    failed = []
    xTickMarks_a = []
    xTickMarks_b = []
    xTickGraph_a = []
    xTickGraph_b = []
    global_max = []
    for key, objs in results.items() :
        tmp_values = []
        for obj in objs:
            tmp_values.append(obj["value"])
        size = len(tmp_values)  
        tmp_values = np.array(tmp_values) 
        global_max.append(np.max(tmp_values))
        values.append(tmp_values)
        
        xTickMarks_a.append(key)
        
    for key, objs in tot_err.items() :
        passed_values = []
        failed_values = []
        objs_range=len(objs[0])
        for i in range(0,objs_range):
            if objs[0][i]["count"]:
                obj1=float(objs[0][i]["count"])
            else:
                obj1=0.0
            if objs[1][i]["count"]:
                obj2=float(objs[1][i]["count"])
            else:
                obj2=0.0
            obj3=obj1+obj2
            failed_values.append(obj1/obj3*100)
            passed_values.append(obj2/obj3*100)
        failed_values = np.array(failed_values) 
        passed_values = np.array(passed_values) 
        passed.append(passed_values)
        failed.append(failed_values)
        xTickMarks_b.append(key)
        
    global_max= (np.max(global_max))   
    ax.set_xlim(left=0)
    ax.set_xlim(right=global_max)
    ax.set_ylim(top=1.2)
    bx.set_ylim(top=100)
    ind = np.arange(len(xTickMarks_b))                # the x locations for the groups
    width = 0.9                      # the width of the bars
    
    # the histogram of the data
    for value in values:
        n, bins, patches = ax.hist(value, bins=100, cumulative=True, normed=True, histtype='step', range=(0,global_max))
        xTickGraph_a.append(patches[0])
    
    bx.set_xlim(left=-0.1) 
    bx.set_xlim(right=2)     
    passed_bar = bx.bar(ind, passed, width, color='b')
    xTickGraph_b.append(passed_bar[0])
    failed_bar = bx.bar(ind, failed, width, color='y',bottom=passed)
    xTickGraph_b.append(failed_bar[0])
    ax.set_xlabel('Total files synced [n]')
    ax.set_ylabel('Probability')
    bx.set_xlabel('Total errors for different machines [n]')
    bx.set_ylabel('Percentage [%]')
    ax.legend(xTickGraph_a,xTickMarks_a)
    bx.legend(xTickGraph_b,('Passed', 'Failed'))
    bx.set_xticks(ind+0.45)
    xtickNames = bx.set_xticklabels(xTickMarks_b)
    plt.setp(xtickNames, rotation=45, fontsize=12)
    ax.grid(True)
    bx.grid(False)
    plt.tight_layout(rect=[0, 0.03, 1, 0.90])
    plt.draw()
    
def run(testset_config): 
    config = testset_config["config"]
    client = InfluxDBClient(config["remote_storage_server"], 8086, config["remote_storage_user"], config["remote_storage_password"], config["remote_database"])
    
    tests = testset_config["tests"] 
    for test in tests:
        if test["test_name"]=="monit":
            for type in test["graph"]:
                if type["show"]==True and type["type"]=="compare-sync":
                    points = {}
                    for server in type["server"]:
                        tot = client.query("SELECT value FROM \"%s-%s\" WHERE runid='%s' and server_name='%s'"%(test["test_name"],"total-syn",type["runid"],server))
                        upl = client.query("SELECT value FROM \"%s-%s\" WHERE runid='%s' and server_name='%s' and worker_name='%s'"%(test["test_name"],"syn",type["runid"],server,"worker0"))
                        dwl = client.query("SELECT value FROM \"%s-%s\" WHERE runid='%s' and server_name='%s' and worker_name='%s'"%(test["test_name"],"syn",type["runid"],server,"worker1"))
                        points[server]=[list(tot.get_points()),list(upl.get_points()),list(dwl.get_points())]
                    compare_monit_sync_graph(points,type["runid"])
                if type["show"]==True and type["type"]=="compare-time":
                    points = {}
                    server = type["server"]
                    tot = client.query("SELECT value FROM \"%s-%s\" WHERE runid='%s' and server_name='%s'"%(test["test_name"],"total-syn",type["runid"],server))
                    points[server]=list(tot.get_points())
                    compare_monit_time_graph(points,type["runid"])
                if type["show"]==True and type["type"]=="cm-histogram-sync":
                    points = {}
                    for server in type["server"]:
                        tot = client.query("SELECT value FROM \"%s-%s\" WHERE runid='%s' and server_name='%s'"%(test["test_name"],"total-syn",type["runid"],server))
                        points[server]=list(tot.get_points())
                    compare_monit_cm_histsync_graph(points,type["runid"])
                if type["show"]==True and type["type"]=="histogram-sync-runid":
                    points = {}
                    server = type["server"]
                    for runid in type["runid"]:
                        tot_upl = client.query("SELECT value FROM \"%s-%s\" WHERE runid='%s' and server_name='%s' and worker_name='worker0' "%(test["test_name"],"syn",runid,server))
                        tot_dwl = client.query("SELECT value FROM \"%s-%s\" WHERE runid='%s' and server_name='%s' and worker_name='worker1' "%(test["test_name"],"syn",runid,server))
                        points[runid]=[list(tot_upl.get_points()),list(tot_dwl.get_points())]
                    compare_monit_histsync_graph(points,server)
                if type["show"]==True and type["type"]=="compare-files-runid":
                    tot_files = {}
                    tot_err = {}
                    server = type["server"]
                    for runid in type["runid"]:
                        tot_files_q = client.query("SELECT value FROM \"%s-%s\" WHERE runid='%s' and server_name='%s'"%(test["test_name"],"total-files",runid,server))
                        tot_failed_q = client.query("SELECT count(value) FROM \"%s-%s\" WHERE runid='%s' and server_name='%s' and worker_name='worker1' and value=1"%(test["test_name"],"err",runid,server))
                        tot_passed_q = client.query("SELECT count(value) FROM \"%s-%s\" WHERE runid='%s' and server_name='%s' and worker_name='worker1' and value=0"%(test["test_name"],"err",runid,server))
                        tot_files[runid]=list(tot_files_q.get_points())
                        tot_err[runid]=[list(tot_failed_q.get_points()),list(tot_passed_q.get_points())]
                    compare_files_runid(tot_files,tot_err,server)
    plt.show()                
def main(arguments):
    analyse_path = os.path.join(os.path.dirname(__file__),'analyse.config')
    if len(arguments)==1 and os.path.exists(analyse_path):
        print "takes %s config path"%analyse_path
        arguments.append(analyse_path)
    for arg_i in range(1, len(arguments)):
        testset_config = get_config(arguments[arg_i])
        run(testset_config)            
       
if __name__ == '__main__':
    """    """
    arguments = sys.argv
    main(arguments)




